#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Arne Neumann <arne-neumann@web.de>

"""
TODO: write argmatch() or use a list e.g. for PATIENS = ["code", "examples"]
TODO: check active vs. passive plus theta roles. check if passive forms in 
HLDS specifically mention AUX (e.g. herausbringen --> WURDE herausgebracht)

TODO: think about alternations. these should not be part of the lexicon, 
though.

    Code: Code-Beispiele, $Programmiersprache-Code, Code in der 
          Programmiersprache $Programmiersprache
    
    Autor: der Autor, $Vorname $Nachname, der Autor $Vorname $Nachname, 
           $Nachname
    Autoren: die Autoren, $Vorname1 $Nachname1 und $Vorname2 $Nachname2, 
             die Autoren $Nachname1 und $Nachname2, $Nachname1 und $Nachname2
    Sprache: in deutscher Sprache, auf Deutsch, deutschsprachig

NOTE: We neither have gender info for authors, nor do we know if a book was 
written in language A (by the author) or was just translated by the publisher 
afterwards!
"""

class Entry(object):
    """
    defines an entry in the lexicon
    """
    def __init__(self, lex_id, pos, required_args, 
                 optional_args, plus_args, grammatical_restrictions):
        self.lex_id = lex_id
        self.pos = pos
        self.required_args = required_args
        self.optional_args = optional_args # regex: A?
        self.plus_args = plus_args # regex: A+
        self.grammatical_restrictions = grammatical_restrictions

class Entries():
    """creates Entry() instances
    
    Each lexicon entry of the form Entry(lex_id, lex_string, pos, 
    required_args, optional_args, plus_args, grammatical_restrictions) is 
    generated by its own method. 
    
    NOTE: These methods have to adhere to a naming convention, i.e. begin with 
    'genentry_'; otherwise, self.__init__ will fail!
    """
        
    def __init__ (self):
        """calls methods to generate entries and saves these in self.entries"""
        self.entries = []
        methods_list = dir(self) #lists all methods of Entries()
        for method_name in methods_list:
            if method_name.startswith('genentry_'):
                method = 'self.' + method_name + '()'
                entry = eval(method) # calls a method that generates a rule
                if type(entry) == Entry:
                    self.entries.append(entry)
                elif type(entry) == list:
                    self.entries.extend(entry)
                    # we can't use append for rules which produce more than one 
                    # entry


    ### authorship and publication rules

    def genentry_publish1(self):
        """
        Der Autor X veröffentlichte das Buch Y im Verlag ABC.
        Im Jahr 1990 veröffentlichte der Autor X sein Buch (Y) (im Verlag ABC)
        
        TODO: add restrictions 'sein/ihr Buch', 'beim/im Verlag'
        """
        required_args = ["author", "title"]
        optional_args = ["publisher", "year"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "author", 
                                    "PATIENS": "title"}
        entry = Entry("veröffentlichen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry
    
    def genentry_publish2a(self):
        """
        Der Verlag ABC veröffentlichte das Buch X (von Noam Chomsky).
        Im Jahr 2120 veröffentlichte der ABC-Verlag (das Buch) Syntax (von Noam 
        Chomsky).
        """
        required_args = ["publisher", "title"]
        optional_args = ["author", "year"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "publisher", 
                                    "PATIENS": "title"}
        entry = Entry("veröffentlichen:2", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry
    
    def genentry_publish2b(self):
        """
        Im Jahr 2000 brachte der ABC-Verlag das Buch X (von Noam C.) heraus.
        Der Verlag ABC brachte "On Syntax" von Chomsky (im Jahr 2000) heraus.
        
        TODO: should be logically equivalent to genentry_publish2(), but linked 
        to a different surface structure (veröffentlichte vs. brachte heraus)
        """
        required_args = ["publisher", "title"]
        optional_args = ["author", "year"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "publisher", 
                                    "PATIENS": "title"}
        entry = Entry("herausbringen:1", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry
    
    def genentry_publish3a(self):
        """
        Das Buch X (von Noam Chomksy) wurde (im Jahr 2000 | im ABC-Verlag)+ 
        herausgebracht.

        TODO: passiv: AGENS == ""?
        TODO: prät: wurde veröffentlicht?
        """
        required_args = ["title"]
        optional_args = ["author"]
        plus_args = ["year", "publisher"]
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("veröffentlichen:3", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry
    
    def genentry_publish3b(self):
        """
        Das Buch X (von Noam Chomksy) wurde (im Jahr 2000 | im ABC-Verlag)+ 
        herausgebracht.
    
        TODO: should be logically equiv. to publish3a
        TODO: passiv: AGENS == ""?
        TODO: prät: wurde herausgebracht?
        """
        required_args = ["title"]
        optional_args = ["author"]
        plus_args = ["year", "publisher"]
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("herausbringen:2", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry
    
    def genentry_publish3c(self):
        """
        Das Buch X (von Noam Chomksy) kam (im Jahr 2000 | im ABC-Verlag)+ 
        heraus.
    
        TODO: should be logically equiv. to publish3a/3b
        TODO: passiv: AGENS == ""?
        TODO: prät: kam heraus?
        """
        required_args = ["title"]
        optional_args = ["author"]
        plus_args = ["year", "publisher"]
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("herauskommen", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry
    
    def genentry_publish4(self):
        """
        (Das Buch) "On Syntax" (von N. Chomsky) erschien (im Jahr 1968 | im 
        Verlag ABC).
        Noam Chomsky's "On Syntax" erschien 1968 im ABC-Verlag.    
        """
        required_args = ["title"]
        optional_args = ["author"]
        plus_args = ["year", "publisher"]
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "title", 
                                    "PATIENS": ""}
        entry = Entry("erscheinen", "V",
                      required_args, optional_args, plus_args,
                      grammatical_restrictions)
        return entry

    def genentry_write1a(self):
        """
        Noam Chomsky schrieb das Buch "On Syntax".
        """
        required_args = ["author", "title"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "author", 
                                    "PATIENS": "title"}
        entry = Entry("schreiben:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_write1b(self):
        """
        Noam Chomsky verfasste das Buch "On Syntax".
        
        TODO: should be logically equiv. to write1a
        """
        required_args = ["author", "title"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "author", 
                                    "PATIENS": "title"}
        entry = Entry("verfassen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_write2a(self):
        """
        Das Buch "On Syntax" wurde von Chomsky geschrieben.
        
        TODO: passive
        """
        required_args = ["author", "title"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("schreiben:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_write2b(self):
        """
        Das Buch "On Syntax" wurde von Chomsky verfasst.
        
        TODO: passive
        TODO: should be logically equiv. to write2a
        """
        required_args = ["author", "title"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("verfassen:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics1a(self):
        """
        (Das Buch) X (des Autors Y) befasst sich mit den Themen A, B und C.
        
        TODO: reflexiv
        """
        required_args = ["title", "keywords"]
        optional_args = ["author"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "keywords"}
        entry = Entry("befassen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry
    
    def genentry_topics1b(self):
        """
        (Das Buch) X (des Autors Y) beschäftigt sich mit den Themen A, B und C.
        
        TODO: reflexiv
        TODO: should be logically equiv. to topics1a
        """
        required_args = ["title", "keywords"]
        optional_args = ["author"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "keywords"}
        entry = Entry("beschäftigen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry
    
    def genentry_topics1c(self):
        """
        (Das Buch) X (des Autors Y) behandelt die Themen A, B und C.

        TODO: should be logically equiv. to topics1a/1b, but is non-reflexive
        """
        required_args = ["title", "keywords"]
        optional_args = ["author"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "keywords"}
        entry = Entry("behandeln:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics1d(self):
        """
        (Das Buch) X (des Autors Y) deckt die Themen A, B und C ab.

        TODO: should be logically equiv. to topics1a/1b/1c, 
              but is non-reflexive
        """
        required_args = ["title", "keywords"]
        optional_args = ["author"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "keywords"}
        entry = Entry("abdecken:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics2a(self):
        """
        (Der Autor) Noam Chomsky befasst sich ((im Buch | in)+ "On Syntax") mit 
        den Themen A, B und C.
        
        NOTE: if we had more time, we could add "in seinem/ihrem" Buch 
        (requires gender info in the database)
        """
        required_args = ["author", "keywords"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "author", 
                                    "PATIENS": "keywords"}
        entry = Entry("befassen:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics2b(self):
        """
        (Der Autor) Noam Chomsky beschäftigt sich ((im Buch | in)+ "On 
        Syntax") mit den Themen A, B und C.
        
        NOTE: if we had more time, we could add "in seinem/ihrem" Buch 
        (requires gender info in the database)
        """
        required_args = ["author", "keywords"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "author", 
                                    "PATIENS": "keywords"}
        entry = Entry("beschäftigen:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics2c(self):
        """
        (Der Autor) Noam Chomsky behandelt ((im Buch | in)+ "On 
        Syntax") die Themen A, B und C.
        
        NOTE: if we had more time, we could add "in seinem/ihrem" Buch 
        (requires gender info in the database)
        """
        required_args = ["author", "keywords"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "author", 
                                    "PATIENS": "keywords"}
        entry = Entry("behandeln:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_topics2d(self):
        """
        (Der Autor) Noam Chomsky deckt ((im Buch | in)+ "On 
        Syntax") die Themen A, B und C.
        
        NOTE: if we had more time, we could add "in seinem/ihrem" Buch 
        (requires gender info in the database)
        """
        required_args = ["author", "keywords"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "author", 
                                    "PATIENS": "keywords"}
        entry = Entry("abdecken:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_code_exercises1(self):
        """
        (Conrad Barskys) "Land of Lisp" enthält zahlreiche Übungen/Code-Bsps.
        
        TODO: grammatical_restrictions require pattern matching (or just a 
        list of str)?
        """
        required_args = ["title"]
        optional_args = ["author"]
        plus_args = ["code", "exercises"]
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": ["code", "examples"]}
        entry = Entry("enthalten:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_code_exercises2(self):
        """
        (Im Buch | In) "Land of Lisp" sind zahlreiche Übungen/Code-Bsp. 
        vorhanden.
        
        TODO: grammatical_restrictions require pattern matching (or just a 
        list of str)?
        
        TODO: passive?
        TODO: is "sein" really an AUX here? vorhanden == ADJ?
        """
        required_args = ["title"]
        optional_args = []
        plus_args = ["code", "exercises"]
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": ["code", "examples"], 
                                    "AUX": "sein"}
        entry = Entry("vorhanden:1", "ADJ",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_code_exercises3a(self):
        """
        (Der Autor) C. Barsky verwendet zahlreiche Code-Bsp., um die Themen 
        des Buches zu erklären.
        (Der Autor) C. Barsky verwendet zahlreiche Code-Bsp. zur Erklärung 
        (der Themen des Buches).

        TODO: grammatical_restrictions require pattern matching (or just a 
        list of str)?
        
        TODO: um zu + inf; zur V.nominalized
        """
        required_args = ["author", "code"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": ["code", "examples"]}
        entry = Entry("erklären:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_code_exercises3b(self):
        """
        (Der Autor) C. Barsky verwendet zahlreiche Code-Bsp., um die Themen 
        des Buches zu erläutern.
        (Der Autor) C. Barsky verwendet zahlreiche Code-Bsp. zur Erläuterung 
        (der Themen des Buches).

        TODO: should be logically equiv. to code_exercises3a
        TODO: grammatical_restrictions require pattern matching (or just a 
        list of str)?
        
        TODO: um zu + inf; zur V.nominalized
        """
        required_args = ["author", "code"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": ["code", "examples"]}
        entry = Entry("erläuterung:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_pages1a(self):
        """
        (Das Buch) "On Syntax" hat einen Umfang von $pages.
        
        TODO: hat == AUX??
        """
        required_args = ["title", "pages"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "pages"}
        entry = Entry("Umfang:1", "N",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_pages1b(self):
        """
        (Das Buch) "On Syntax" umfasst $pages Seiten.
        """
        required_args = ["title", "pages"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "pages"}
        entry = Entry("umfassen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_pages1c(self):
        """
        (Das Buch) "On Syntax" ist $pages Seiten lang.
        
        TODO: sein == AUX?? ist lang
        """
        required_args = ["title", "pages"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "pages"}
        entry = Entry("lang:1", "ADJ",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_pages1d(self):
        """
        $pagerange::

            0: (eher) kurz
            1: durchschnittlich lang
            2: sehr lang / sehr umfangreich

        (Das Buch) "On Syntax" ist mit $pages Seiten $pagerange.
        """
        entries = []
        pageranges = {}
        pageranges["0"] = {"lex_id": "kurz:1", "pos": "ADJ", "MOD": "eher"}
        pageranges["1"] = {"lex_id": "lang:2", "pos": "ADJ", 
                          "MOD": "durchschnittlich"}
        pageranges["2"] = {"lex_id": "lang:3", "pos": "ADJ", "MOD": "sehr"}
        
        required_args = ["title", "pages", "pagerange"]
        optional_args = []
        plus_args = []
        
        for _index, pagerange in pageranges.items():
            grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                        "PATIENS": "pagerange", "AUX": "sein",
                                        "MOD": pagerange["MOD"]}

            entry = Entry(pagerange["lex_id"], pagerange["pos"],
                          required_args, optional_args, plus_args, 
                          grammatical_restrictions)
            entries.append(entry)
        return entries

    def genentry_language1(self):
        """
        (Das Buch) "On Syntax" ist (in deutscher Sprache | auf Deutsch) verfasst
        """
        required_args = ["title", "language"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("verfassen:3", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_language2(self):
        """
        (Das Buch) "On Syntax" ist deutschsprachig.
    
        TODO: "sprachig" == part, particle of sth. or ADJ??
    
\item[erscheinen / wurde\_veröffentlicht] {\tt author?, title, publisher, language, year*} \\
    (\$year) erschien \$title in im Verlag \$publisher in \$language Sprache.
    \$author s \$title wurde \$year vom Verlag \$publisher auf \$language veröffentlicht.

        """
        required_args = ["title", "language"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "", 
                                    "PATIENS": "title", "AUX": "sein",
                                    "MOD": "language"}
        entry = Entry("sprachig:1", "PART",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_language3a(self):
        """
        (Chomsky's | Das Buch) "On Syntax" erschien (1963) (in englischer 
        Sprache | auf Englisch) im ABC-Verlag.
    
    
\item[erscheinen / wurde\_veröffentlicht] {\tt author?, title, publisher, language, year*} \\
    (\$year) erschien \$title in im Verlag \$publisher in \$language Sprache.
    \$author s \$title wurde \$year vom Verlag \$publisher auf \$language veröffentlicht.

        """
        required_args = ["title", "publisher", "language"]
        optional_args = ["author", "year"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("erscheinen:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_language3b(self):
        """
        (Chomsky's | Das Buch) "On Syntax" wurde (1963) (in englischer 
        Sprache | auf Englisch) im ABC-Verlag veröffentlicht.
    
        TODO: should be logically equiv. to language3a, but needs an AUX 
        (sein/wurde)
        """
        required_args = ["title", "publisher", "language"]
        optional_args = ["author", "year"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title", "AUX": "sein"}
        entry = Entry("veröffentlichen:4", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target1(self):
        """
        (Chomsky's | Das Buch) "On Syntax" richtet sich an $target

        TODO: specify different targets (cf. pagerange differentiations)
        """
        required_args = ["title", "target"]
        optional_args = ["author"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "title", 
                                    "PATIENS": "target"}
        entry = Entry("richten:1", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target2(self):
        """
        Noam Chomsky richtet sich (in "On Syntax") an $target.
        Der Autor richtet sich (im Buch) an ein $target-Publikum.
        
        NOTE: no gender info in database --> no "in seinem/ihrem Buch"
        """
        required_args = ["author", "target"]
        optional_args = ["title"]
        plus_args = []
        grammatical_restrictions = {"TEMP": "präs", "AGENS": "author", 
                                    "PATIENS": "target"}
        entry = Entry("richten:2", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target3a(self):
        """
        (Das Buch) "On Syntax" wurde für $target geschrieben.
        Das Buch wurde für ein $target-Publikum geschrieben.
        """
        required_args = ["title", "target"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("schreiben:3", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target3b(self):
        """
        (Das Buch) "On Syntax" wurde für $target verfasst.
        Das Buch wurde für ein $target-Publikum verfasst.
        
        TODO: should be logically equivalent to target3a
        """
        required_args = ["title", "target"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "", 
                                    "PATIENS": "title"}
        entry = Entry("verfassen:4", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target4a(self):
        """
        (Der Autor) Noam Chomsky schrieb "On Syntax" für ($target | ein 
        $target-Publikum).
        """
        required_args = ["author", "title", "target"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "author", 
                                    "PATIENS": "title"}
        entry = Entry("schreiben:4", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

    def genentry_target4b(self):
        """
        (Der Autor) Noam Chomsky verfasste "On Syntax" für ($target | ein 
        $target-Publikum).
    
        TODO: should be logically equivalent to target4a
        """
        required_args = ["author", "title", "target"]
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "prät", "AGENS": "author", 
                                    "PATIENS": "title"}
        entry = Entry("verfassen:4", "V",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry


'''

    def genentry_template(self):
        """
        """
        required_args = []
        optional_args = []
        plus_args = []
        grammatical_restrictions = {"TEMP": "", "AGENS": "", 
                                    "PATIENS": ""}
        entry = Entry("", "",
                      required_args, optional_args, plus_args, 
                      grammatical_restrictions)
        return entry

'''

def non_unique_ids(entries):
    """
    helper function that returns a list of lexicon IDs that occur more than 
    once (which should not happen). returns None if everything is OK.
    """
    lex_id_list = []
    for entry in entries.entries:
        lex_id_list.append(entry.lex_id)
    if len(lex_id_list) == len(set(lex_id_list)):
        return None
    else:
        lex_id_set = set()
        non_uniques = set()
        for lex_id in lex_id_list:
            if lex_id in lex_id_set:
                non_uniques.add(lex_id)
            else:
                lex_id_set.add(lex_id)
        return list(non_uniques)

#def argmatch(arg1, arg2):
    #"""
    #helper function to check if two strings are equal OR if a regular 
    #expression matches a complete string. this could be used when ensuring 
    #that all grammatical_restrictions in the lexicon are met.
    
    #IO specification::
    
        #>>> argmatch("foo","foo")
        #True
        #>>> argmatch("foo","food")
        #False
        #>>> regex = re.compile("foo|bar")
        #>>> argmatch("foo", regex)
        #True
        #>>> argmatch("food", regex)
        #False
        #>>> argmatch(regex, "bar")
        #True
        #>>> argmatch(regex, "bart")
        #False                   
    #"""
    #pass

if __name__ == "__main__":
    entries = Entries()
    non_uniques = non_unique_ids(entries)
    if non_uniques:
        raise Exception, \
              "These lexicon IDs aren't unique: {0}".format(non_uniques)
